// ===== 1. Main Container Component =====
// src/pages/AdminHotspotMap.jsx
import React, { useEffect, useState, useMemo } from "react";
import toast from "react-hot-toast";
import AdminHeader from "../../components/admin/AdminHeader";
import StatisticsCards from "../../components/admin/StatisticsCards";
import LoadingSkeleton from "../../components/admin/LoadingSkeleton";
import MapFilters from "../../components/map/MapFilters";
import InteractiveMap from "../../components/map/InteractiveMap";
import MapLegend from "../../components/map/MapLegend";
import axios from "axios";

const AdminHotspotMap = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filterPriority, setFilterPriority] = useState("All");
  const [filterStatus, setFilterStatus] = useState("All");
  const [filterCategory, setFilterCategory] = useState("All");
  const [mapStyle, setMapStyle] = useState("default");

  const adminUser = {
    name: "Admin Demo",
    role: "GIS Administrator",
    department: "Urban Planning Department",
  };

  // ------------------- Updated fetchReports -------------------
  const fetchReports = async (trackingId = "") => {
    setLoading(true);
    try {
      const res = await axios.get("http://localhost:5000/api/reports", {
        params: trackingId ? { trackingId } : {},
      });

      if (!res.data.success) throw new Error("Failed to fetch reports");

      const parsedData = res.data.reports.map((r) => ({
        ...r,
        mediaFiles: Array.isArray(r.mediaFiles) ? r.mediaFiles : [],
        addressData: {
          address: r.addressData?.address || "",
          city: r.addressData?.city || "",
          district: r.addressData?.district || "",
          state: r.addressData?.state || "",
          stateCode: r.addressData?.stateCode || "",
          country: r.addressData?.country || "India",
          pincode: r.addressData?.pincode || "",
        },
        status: r.status || "Pending",
        priority: r.priority || "Low",
        trackingId: r.trackingId || "", // already generated by backend
      }));

      setReports(parsedData);
    } catch (err) {
      console.error("❌ Error fetching reports:", err);
      toast.error("Failed to load reports for map");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  // ------------------- Filtered reports -------------------
  const filteredReports = useMemo(() => {
    return reports.filter((report) => {
      if (!report.lat || !report.lng) return false;
      if (filterPriority !== "All" && report.priority !== filterPriority)
        return false;
      if (filterStatus !== "All" && report.status !== filterStatus) return false;
      if (filterCategory !== "All" && report.category !== filterCategory)
        return false;
      return true;
    });
  }, [reports, filterPriority, filterStatus, filterCategory]);

  // ------------------- Statistics -------------------
  const getStatistics = () => ({
    total: filteredReports.length,
    pending: filteredReports.filter((r) => r.status === "Pending").length,
    inProgress: filteredReports.filter((r) => r.status === "In Progress").length,
    resolved: filteredReports.filter((r) => r.status === "Resolved").length,
    highPriority: filteredReports.filter((r) => r.priority === "High").length,
    mediumPriority: filteredReports.filter((r) => r.priority === "Medium").length,
  });

  const uniqueCategories = useMemo(() => {
    return [...new Set(reports.map((r) => r.category).filter(Boolean))];
  }, [reports]);

  // ------------------- Export CSV -------------------
  const exportMapData = () => {
    const csvData = [
      ["ID", "Category", "Priority", "Status", "Latitude", "Longitude", "Address"],
      ...filteredReports.map((r) => [
        r.id,
        r.category,
        r.priority,
        r.status,
        r.lat,
        r.lng,
        r.addressData?.address || "",
      ]),
    ]
      .map((row) => row.join(","))
      .join("\n");

    const blob = new Blob([csvData], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `hotspot_map_data_${new Date().toISOString()}.csv`;
    a.click();
    toast.success("Map data exported successfully");
  };

  const clearFilters = () => {
    setFilterPriority("All");
    setFilterStatus("All");
    setFilterCategory("All");
  };

  const handleReportClick = (report) => {
    toast.success(`Viewing details for Report #${report.id}`);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50 dark:from-gray-900 dark:to-gray-800 flex items-center justify-center">
        <LoadingSkeleton />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50 dark:from-gray-900 dark:to-gray-800 py-6 px-4">
      <div className="max-w-7xl mx-auto">
        <AdminHeader
          adminUser={adminUser}
          onExport={exportMapData}
          title="Issue Hotspot Map"
          subtitle="Geographic visualization of all reported civic issues"
        />

        <StatisticsCards statistics={getStatistics()} />

        <MapFilters
          filterPriority={filterPriority}
          setFilterPriority={setFilterPriority}
          filterStatus={filterStatus}
          setFilterStatus={setFilterStatus}
          filterCategory={filterCategory}
          setFilterCategory={setFilterCategory}
          categories={uniqueCategories}
          mapStyle={mapStyle}
          setMapStyle={setMapStyle}
          onClearFilters={clearFilters}
        />

        <InteractiveMap
          reports={filteredReports}
          mapStyle={mapStyle}
          onReportClick={handleReportClick}
        />

        <MapLegend />
      </div>
    </div>
  );
};

export default AdminHotspotMap;
